# Generated by Django 4.2.8 on 2024-01-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="rating",
            field=models.IntegerField(default=1),
        ),
    ]
