# Generated by Django 4.2.8 on 2024-01-18 09:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_clients", "0002_client_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="rating",
        ),
    ]
