# Generated by Django 4.2.8 on 2023-12-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Запрещенный товар", "Запрещенный товар"),
                            ("Спам", "Спам"),
                            ("Дубликат", "Дубликат"),
                            ("Неверная категория", "Неверная категория"),
                            ("Мошенничество", "Мошенничество"),
                            ("Другая причина", "Другая причина"),
                        ],
                        default="Спам",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
