# Generated by Django 4.2.8 on 2024-01-06 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_complaint", "0001_initial"),
        ("app_clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaint",
                to="app_clients.client",
            ),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(fields=["id"], name="app_complai_id_aff01f_idx"),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["-created_at"], name="app_complai_created_5c5355_idx"
            ),
        ),
    ]
