# Generated by Django 4.2.8 on 2023-12-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_complaint", "0003_complaint_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="product",
        ),
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("Запрещенный товар", "Запрещенный товар"),
                    ("Спам", "Спам"),
                    ("Дубликат", "Дубликат"),
                    ("Неверная категория", "Неверная категория"),
                    ("Мошенничество", "Мошенничество"),
                    ("Другая причина", "Другая причина"),
                ],
                default="Спам",
                max_length=20,
            ),
        ),
    ]
