# Generated by Django 4.2.8 on 2024-01-10 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_products", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
