# Generated by Django 4.2.8 on 2024-01-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_clients", "0001_initial"),
        ("app_products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_clients.client"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["id", "slug"], name="app_product_id_4eae13_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["title"], name="app_product_title_6056e6_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created"], name="app_product_created_79dcf2_idx"
            ),
        ),
    ]
