# Generated by Django 4.2.8 on 2023-12-22 03:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_complaint", "0004_remove_complaint_product_alter_complaint_status"),
        ("app_products", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
