# Generated by Django 4.2.8 on 2024-01-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_products", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "⭐️"),
                    (2, "⭐️⭐️"),
                    (3, "⭐️⭐️⭐️"),
                    (4, "⭐️⭐️⭐️⭐️"),
                    (5, "⭐️⭐️⭐️⭐️⭐️"),
                ],
                null=True,
            ),
        ),
    ]
