# Generated by Django 4.2.8 on 2024-01-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_products", "0002_delete_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
    ]
