# Generated by Django 4.2.8 on 2024-02-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_products", "0002_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="app_product_id_4eae13_idx",
        ),
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["id"], name="app_product_id_6d7098_idx"),
        ),
    ]
