# Generated by Django 4.2.8 on 2024-01-17 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_products", "0003_product_location_product_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="rating",
        ),
        migrations.CreateModel(
            name="RatingProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "⭐️"),
                            (2, "⭐️⭐️"),
                            (3, "⭐️⭐️⭐️"),
                            (4, "⭐️⭐️⭐️⭐️"),
                            (5, "⭐️⭐️⭐️⭐️⭐️"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_products.product",
                    ),
                ),
            ],
        ),
    ]
