# Generated by Django 4.2.8 on 2024-01-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_products", "0003_remove_product_images_product_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="images",
        ),
        migrations.AddField(
            model_name="product",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image4",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/%Y/%m/%d/"
            ),
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
