# Generated by Django 4.2.8 on 2024-01-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_products", "0003_product_location_product_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
