# Generated by Django 4.2.8 on 2024-01-17 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_clients", "0001_initial"),
        ("app_products", "0004_remove_product_rating_ratingproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="ratingproduct",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_clients.client",
            ),
            preserve_default=False,
        ),
    ]
