# Generated by Django 4.2.8 on 2024-01-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_like", "0001_initial"),
        ("app_products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="app_products.product",
            ),
        ),
    ]
