# Generated by Django 4.2.8 on 2024-01-17 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_like", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="app_products.product",
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "product")},
        ),
    ]
