# Generated by Django 4.2.8 on 2023-12-22 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_chat", "0002_remove_chat_message_remove_chat_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="owner",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_chat",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
