# Generated by Django 4.2.8 on 2024-02-11 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_clients", "0001_initial"),
        ("app_chat", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="participants",
        ),
        migrations.AddField(
            model_name="chat",
            name="participants",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to="app_clients.client",
            ),
            preserve_default=False,
        ),
    ]
