# Generated by Django 4.2.8 on 2023-12-22 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_clients", "0001_initial"),
        ("app_chat", "0003_chat_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_chat",
                to="app_clients.client",
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="participants",
            field=models.ManyToManyField(related_name="chats", to="app_clients.client"),
        ),
    ]
