# Generated by Django 4.2.8 on 2024-02-11 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_chat", "0004_alter_chat_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="content",
            new_name="message",
        ),
    ]
