# Generated by Django 4.2.8 on 2024-02-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_clients", "0001_initial"),
        ("app_chat", "0005_rename_content_message_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_chat",
                to="app_clients.client",
            ),
        ),
    ]
