# Generated by Django 4.2.8 on 2024-01-06 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_support_servise", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportchat",
            name="recipient",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="received_chats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supportchat",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_chats",
                to="app_clients.client",
            ),
        ),
    ]
