# Generated by Django 4.2.8 on 2023-12-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatar/%Y/%m/%d/"
            ),
        ),
    ]
