# Generated by Django 4.2.8 on 2023-12-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="activation_code",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
