# Generated by Django 4.2.8 on 2024-01-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "⭐️"),
                    (2, "⭐️⭐️"),
                    (3, "⭐️⭐️⭐️"),
                    (4, "⭐️⭐️⭐️⭐️"),
                    (5, "⭐️⭐️⭐️⭐️⭐️"),
                ],
                null=True,
            ),
        ),
    ]
