# Generated by Django 4.2.8 on 2024-01-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="rating",
        ),
        migrations.AddField(
            model_name="customuser",
            name="client_rating",
            field=models.IntegerField(null=True),
        ),
    ]
