# Generated by Django 4.2.8 on 2024-02-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0003_alter_customuser_client_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="client_rating",
            field=models.IntegerField(null=True),
        ),
    ]
