# Generated by Django 4.2.8 on 2024-02-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0005_remove_customuser_client_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
