# Generated by Django 4.2.8 on 2024-01-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo1",
                    models.ImageField(
                        blank=True, null=True, upload_to="comment/%Y/%m/%d/"
                    ),
                ),
                (
                    "photo2",
                    models.ImageField(
                        blank=True, null=True, upload_to="comment/%Y/%m/%d/"
                    ),
                ),
                (
                    "photo3",
                    models.ImageField(
                        blank=True, null=True, upload_to="comment/%Y/%m/%d/"
                    ),
                ),
                (
                    "photo4",
                    models.ImageField(
                        blank=True, null=True, upload_to="comment/%Y/%m/%d/"
                    ),
                ),
                ("is_sub", models.BooleanField(default=False)),
                ("body", models.TextField()),
                ("register_date", models.DateTimeField(auto_now_add=True)),
                ("is_confirm", models.BooleanField(default=False)),
            ],
        ),
    ]
