# Generated by Django 4.2.8 on 2024-01-18 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_clients", "0003_remove_client_rating"),
        (
            "app_products",
            "0004_remove_product_images_product_image1_product_image2_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo1",
                    models.ImageField(
                        blank=True, null=True, upload_to="comments/%Y/%m/%d/"
                    ),
                ),
                (
                    "photo2",
                    models.ImageField(
                        blank=True, null=True, upload_to="comments/%Y/%m/%d/"
                    ),
                ),
                (
                    "photo3",
                    models.ImageField(
                        blank=True, null=True, upload_to="comments/%Y/%m/%d/"
                    ),
                ),
                (
                    "photo4",
                    models.ImageField(
                        blank=True, null=True, upload_to="comments/%Y/%m/%d/"
                    ),
                ),
                ("is_sub", models.BooleanField(default=False)),
                ("body", models.TextField()),
                ("register_date", models.DateTimeField(auto_now_add=True)),
                ("is_confirm", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="app_products.product",
                    ),
                ),
                (
                    "sub_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcomments",
                        to="app_comment.comment",
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="app_clients.client",
                    ),
                ),
            ],
        ),
    ]
