# Generated by Django 4.2.8 on 2024-01-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_comment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="photo1",
            field=models.ImageField(
                blank=True, null=True, upload_to="comment/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="photo2",
            field=models.ImageField(
                blank=True, null=True, upload_to="comment/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="photo3",
            field=models.ImageField(
                blank=True, null=True, upload_to="comment/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="photo4",
            field=models.ImageField(
                blank=True, null=True, upload_to="comment/%Y/%m/%d/"
            ),
        ),
    ]
