# Generated by Django 4.2.8 on 2024-01-31 17:14

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("app_comment", "0004_comment_created_at"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="comment",
            managers=[
                ("confirmed", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="writer",
            new_name="author",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="is_sub",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="register_date",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="sub_comment",
        ),
    ]
