# Generated by Django 4.2.8 on 2024-01-31 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_comment",
            "0005_alter_comment_managers_rename_writer_comment_author_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="comment",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="comment",
            name="is_confirm",
        ),
    ]
