# Generated by Django 4.2.8 on 2024-02-01 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_clients", "0001_initial"),
        ("app_comment", "0006_alter_comment_managers_remove_comment_is_confirm"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "Comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_comment.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_clients.client",
                    ),
                ),
            ],
        ),
    ]
