# Generated by Django 4.2.8 on 2024-02-01 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_comment", "0007_commentrating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentrating",
            old_name="Comment",
            new_name="comment",
        ),
    ]
