# Generated by Django 4.2.8 on 2024-02-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_comment", "0008_rename_comment_commentrating_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentrating",
            name="rating",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "⭐️"),
                    (2, "⭐️⭐️"),
                    (3, "⭐️⭐️⭐️"),
                    (4, "⭐️⭐️⭐️⭐️"),
                    (5, "⭐️⭐️⭐️⭐️⭐️"),
                ],
                null=True,
            ),
        ),
    ]
