# Generated by Django 4.2.8 on 2024-02-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_comment", "0009_alter_commentrating_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentrating",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "⭐️"),
                    (2, "⭐️⭐️"),
                    (3, "⭐️⭐️⭐️"),
                    (4, "⭐️⭐️⭐️⭐️"),
                    (5, "⭐️⭐️⭐️⭐️⭐️"),
                ],
                null=True,
            ),
        ),
    ]
