# Generated by Django 4.2.8 on 2024-02-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_comment", "0010_alter_commentrating_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
