# Generated by Django 4.2.8 on 2024-02-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_comment", "0011_alter_comment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentrating",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "⭐️"),
                    (2, "⭐️⭐️"),
                    (3, "⭐️⭐️⭐️"),
                    (4, "⭐️⭐️⭐️⭐️"),
                    (5, "⭐️⭐️⭐️⭐️⭐️"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
    ]
