# Generated by Django 4.2.8 on 2024-02-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_comment", "0012_alter_commentrating_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "⭐️"),
                    (2, "⭐️⭐️"),
                    (3, "⭐️⭐️⭐️"),
                    (4, "⭐️⭐️⭐️⭐️"),
                    (5, "⭐️⭐️⭐️⭐️⭐️"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="CommentRating",
        ),
    ]
