# Generated by Django 4.2.8 on 2024-02-11 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_category", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="podcategory",
            name="slug",
        ),
    ]
