# Generated by Django 4.2.8 on 2024-02-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_category", "0002_remove_category_slug_remove_podcategory_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="img",
            field=models.ImageField(upload_to="products/%Y/%m/%d"),
        ),
        migrations.AlterField(
            model_name="podcategory",
            name="img",
            field=models.ImageField(upload_to="Podcategory/%Y/%m/%d"),
        ),
    ]
